---
- hosts: webservers
  remote_user: root
  become: yes
  tasks:
  - name: install httpd package
    yum: name=httpd state=installed
  - name: copy index.html files
    copy: src=index.html dest=/var/www/html
  - name: start httpd service
    service: name=httpd state=started
    register: output
  - debug:
      msg: "{{output}}"
